name: Windows Build

on:
  workflow_call:
    inputs:
      ring-version:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
        - arch: Win32
          arch_name: i386
          msvc_arch: x64_x86
        - arch: x64
          arch_name: amd64
          msvc_arch: x64
        - arch: ARM64
          arch_name: arm64
          msvc_arch: x64_arm64

    steps:
    - name: Checkout ring-cffi
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Clone Ring Source
      uses: actions/checkout@v6
      with:
        repository: ringpackages/ringsrc
        path: ring
        ref: ${{ inputs.ring-version }}

    - name: Set up MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.msvc_arch }}

    - name: Configure and Build Ring Language for ${{ matrix.arch_name }}
      shell: cmd
      run: |
        cd ring/language
        cmake . -A ${{ matrix.arch }}
        cmake --build . --config Release --parallel
        cmake --install .

    - name: Set RING environment variable
      shell: pwsh
      run: |
        $ringPath = Join-Path (Get-Location) "ring"
        echo "RING=$ringPath" >> $env:GITHUB_ENV

    - name: Configure and Build ring-cffi lib for ${{ matrix.arch_name }}
      shell: cmd
      run: |
        if exist lib rmdir /s /q lib
        cmake . -A ${{ matrix.arch }}
        cmake --build . --config Release --parallel

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ring-cffi-windows-${{ matrix.arch_name }}
        path: lib